package main

import (
	"fmt"
	"path/filepath"
	"strings"

	registryv1 "schema-registry/registry/v1"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func hasEventTypeOption(msg *protogen.Message) (string, bool) {
	opts := msg.Desc.Options()
	if opts == nil {
		return "", false
	}
	if !proto.HasExtension(opts, registryv1.E_EventType) {
		return "", false
	}
	val := proto.GetExtension(opts, registryv1.E_EventType)
	s, ok := val.(string)
	if !ok || strings.TrimSpace(s) == "" {
		return "", false
	}
	return s, true
}

func getAggregateIDField(msg *protogen.Message) (*protogen.Field, error) {
	var found *protogen.Field
	for _, field := range msg.Fields {
		opts := field.Desc.Options()
		if opts == nil {
			continue
		}
		if !proto.HasExtension(opts, registryv1.E_IsAggregateId) {
			continue
		}
		val := proto.GetExtension(opts, registryv1.E_IsAggregateId)
		if b, ok := val.(bool); !ok || !b {
			continue
		}
		if found != nil {
			return nil, fmt.Errorf(
				"message %s: multiple fields have (registry.v1.is_aggregate_id) = true (e.g. %s and %s)",
				msg.Desc.FullName(), found.Desc.Name(), field.Desc.Name(),
			)
		}
		found = field
	}
	if found == nil {
		return nil, fmt.Errorf(
			"message %s: no field has (registry.v1.is_aggregate_id) = true; exactly one is required",
			msg.Desc.FullName(),
		)
	}
	return found, nil
}

// goEventsFilename returns the output filename for the events helper file (e.g. user/v1/user.pb.events.go).
func goEventsFilename(protoPath string) string {
	dir := filepath.Dir(protoPath)
	base := filepath.Base(protoPath)
	name := strings.TrimSuffix(base, filepath.Ext(base))
	return filepath.Join(dir, name+".pb.events.go")
}

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	var events []struct {
		msg       *protogen.Message
		eventType string
		aggField  *protogen.Field
	}
	for _, msg := range file.Messages {
		eventType, ok := hasEventTypeOption(msg)
		if !ok {
			continue
		}
		aggField, err := getAggregateIDField(msg)
		if err != nil {
			gen.Error(err)
			return err
		}
		events = append(events, struct {
			msg       *protogen.Message
			eventType string
			aggField  *protogen.Field
		}{msg, eventType, aggField})
	}
	if len(events) == 0 {
		return nil
	}

	needFmt := false
	for _, e := range events {
		if e.aggField.Desc.Kind() != protoreflect.StringKind {
			needFmt = true
			break
		}
	}

	filename := goEventsFilename(file.Desc.Path())
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-events. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	if needFmt {
		g.P()
		g.P("import \"fmt\"")
	}
	g.P()

	for _, e := range events {
		msg := e.msg
		eventType := e.eventType
		agg := e.aggField
		g.P("// EventType returns the event type string for ", msg.GoIdent.GoName, ".")
		g.P("func (x *", msg.GoIdent.GoName, ") EventType() string {")
		g.P("	return ", quoteGoString(eventType))
		g.P("}")
		g.P()
		g.P("// AggregateId returns the aggregate ID for ", msg.GoIdent.GoName, ".")
		g.P("func (x *", msg.GoIdent.GoName, ") AggregateId() string {")
		if agg.Desc.Kind() == protoreflect.StringKind {
			g.P("	return x.Get", agg.GoName, "()")
		} else {
			g.P("	return fmt.Sprintf(\"%v\", x.Get", agg.GoName, "())")
		}
		g.P("}")
		g.P()
	}
	return nil
}

func quoteGoString(s string) string {
	return fmt.Sprintf("%q", s)
}

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)
		gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO2
		gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2023

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generateFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}
