// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: registry/v1/envelope.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structured CloudEvents envelope
// https://github.com/cloudevents/spec/blob/main/cloudevents/formats/cloudevents.proto
type Envelope struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Source      string                 `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Specversion string                 `protobuf:"bytes,3,opt,name=specversion" json:"specversion,omitempty"` // "1.0"
	Type        string                 `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	// Use a map for extensibility (correlation_id, etc.)
	Attributes map[string]*CloudEventAttributeValue `protobuf:"bytes,5,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to DataOneof:
	//
	//	*Envelope_BinaryData
	//	*Envelope_TextData
	DataOneof     isEnvelope_DataOneof   `protobuf_oneof:"data_oneof"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_registry_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_registry_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Envelope) GetSpecversion() string {
	if x != nil {
		return x.Specversion
	}
	return ""
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetAttributes() map[string]*CloudEventAttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Envelope) GetDataOneof() isEnvelope_DataOneof {
	if x != nil {
		return x.DataOneof
	}
	return nil
}

func (x *Envelope) GetBinaryData() []byte {
	if x != nil {
		if x, ok := x.DataOneof.(*Envelope_BinaryData); ok {
			return x.BinaryData
		}
	}
	return nil
}

func (x *Envelope) GetTextData() string {
	if x != nil {
		if x, ok := x.DataOneof.(*Envelope_TextData); ok {
			return x.TextData
		}
	}
	return ""
}

func (x *Envelope) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type isEnvelope_DataOneof interface {
	isEnvelope_DataOneof()
}

type Envelope_BinaryData struct {
	BinaryData []byte `protobuf:"bytes,6,opt,name=binary_data,json=binaryData,oneof"`
}

type Envelope_TextData struct {
	TextData string `protobuf:"bytes,7,opt,name=text_data,json=textData,oneof"` // You can also use google.protobuf.Any here for direct proto support
}

func (*Envelope_BinaryData) isEnvelope_DataOneof() {}

func (*Envelope_TextData) isEnvelope_DataOneof() {}

type CloudEventAttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Attr:
	//
	//	*CloudEventAttributeValue_CeBoolean
	//	*CloudEventAttributeValue_CeInteger
	//	*CloudEventAttributeValue_CeString
	//	*CloudEventAttributeValue_CeBytes
	//	*CloudEventAttributeValue_CeUri
	//	*CloudEventAttributeValue_CeUriReference
	//	*CloudEventAttributeValue_CeTimestamp
	Attr          isCloudEventAttributeValue_Attr `protobuf_oneof:"attr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudEventAttributeValue) Reset() {
	*x = CloudEventAttributeValue{}
	mi := &file_registry_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudEventAttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudEventAttributeValue) ProtoMessage() {}

func (x *CloudEventAttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudEventAttributeValue.ProtoReflect.Descriptor instead.
func (*CloudEventAttributeValue) Descriptor() ([]byte, []int) {
	return file_registry_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *CloudEventAttributeValue) GetAttr() isCloudEventAttributeValue_Attr {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *CloudEventAttributeValue) GetCeBoolean() bool {
	if x != nil {
		if x, ok := x.Attr.(*CloudEventAttributeValue_CeBoolean); ok {
			return x.CeBoolean
		}
	}
	return false
}

func (x *CloudEventAttributeValue) GetCeInteger() int32 {
	if x != nil {
		if x, ok := x.Attr.(*CloudEventAttributeValue_CeInteger); ok {
			return x.CeInteger
		}
	}
	return 0
}

func (x *CloudEventAttributeValue) GetCeString() string {
	if x != nil {
		if x, ok := x.Attr.(*CloudEventAttributeValue_CeString); ok {
			return x.CeString
		}
	}
	return ""
}

func (x *CloudEventAttributeValue) GetCeBytes() []byte {
	if x != nil {
		if x, ok := x.Attr.(*CloudEventAttributeValue_CeBytes); ok {
			return x.CeBytes
		}
	}
	return nil
}

func (x *CloudEventAttributeValue) GetCeUri() string {
	if x != nil {
		if x, ok := x.Attr.(*CloudEventAttributeValue_CeUri); ok {
			return x.CeUri
		}
	}
	return ""
}

func (x *CloudEventAttributeValue) GetCeUriReference() string {
	if x != nil {
		if x, ok := x.Attr.(*CloudEventAttributeValue_CeUriReference); ok {
			return x.CeUriReference
		}
	}
	return ""
}

func (x *CloudEventAttributeValue) GetCeTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Attr.(*CloudEventAttributeValue_CeTimestamp); ok {
			return x.CeTimestamp
		}
	}
	return nil
}

type isCloudEventAttributeValue_Attr interface {
	isCloudEventAttributeValue_Attr()
}

type CloudEventAttributeValue_CeBoolean struct {
	CeBoolean bool `protobuf:"varint,1,opt,name=ce_boolean,json=ceBoolean,oneof"`
}

type CloudEventAttributeValue_CeInteger struct {
	CeInteger int32 `protobuf:"varint,2,opt,name=ce_integer,json=ceInteger,oneof"`
}

type CloudEventAttributeValue_CeString struct {
	CeString string `protobuf:"bytes,3,opt,name=ce_string,json=ceString,oneof"`
}

type CloudEventAttributeValue_CeBytes struct {
	CeBytes []byte `protobuf:"bytes,4,opt,name=ce_bytes,json=ceBytes,oneof"`
}

type CloudEventAttributeValue_CeUri struct {
	CeUri string `protobuf:"bytes,5,opt,name=ce_uri,json=ceUri,oneof"`
}

type CloudEventAttributeValue_CeUriReference struct {
	CeUriReference string `protobuf:"bytes,6,opt,name=ce_uri_reference,json=ceUriReference,oneof"`
}

type CloudEventAttributeValue_CeTimestamp struct {
	CeTimestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ce_timestamp,json=ceTimestamp,oneof"`
}

func (*CloudEventAttributeValue_CeBoolean) isCloudEventAttributeValue_Attr() {}

func (*CloudEventAttributeValue_CeInteger) isCloudEventAttributeValue_Attr() {}

func (*CloudEventAttributeValue_CeString) isCloudEventAttributeValue_Attr() {}

func (*CloudEventAttributeValue_CeBytes) isCloudEventAttributeValue_Attr() {}

func (*CloudEventAttributeValue_CeUri) isCloudEventAttributeValue_Attr() {}

func (*CloudEventAttributeValue_CeUriReference) isCloudEventAttributeValue_Attr() {}

func (*CloudEventAttributeValue_CeTimestamp) isCloudEventAttributeValue_Attr() {}

var file_registry_v1_envelope_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "registry.v1.event_type",
		Tag:           "bytes,50001,opt,name=event_type",
		Filename:      "registry/v1/envelope.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "registry.v1.is_aggregate_id",
		Tag:           "varint,50002,opt,name=is_aggregate_id",
		Filename:      "registry/v1/envelope.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string event_type = 50001;
	E_EventType = &file_registry_v1_envelope_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool is_aggregate_id = 50002;
	E_IsAggregateId = &file_registry_v1_envelope_proto_extTypes[1]
)

var File_registry_v1_envelope_proto protoreflect.FileDescriptor

const file_registry_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1aregistry/v1/envelope.proto\x12\vregistry.v1\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x03\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vspecversion\x18\x03 \x01(\tR\vspecversion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12E\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2%.registry.v1.Envelope.AttributesEntryR\n" +
	"attributes\x12!\n" +
	"\vbinary_data\x18\x06 \x01(\fH\x00R\n" +
	"binaryData\x12\x1d\n" +
	"\ttext_data\x18\a \x01(\tH\x00R\btextData\x12.\n" +
	"\x04time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x1ad\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.registry.v1.CloudEventAttributeValueR\x05value:\x028\x01B\f\n" +
	"\n" +
	"data_oneof\"\xa6\x02\n" +
	"\x18CloudEventAttributeValue\x12\x1f\n" +
	"\n" +
	"ce_boolean\x18\x01 \x01(\bH\x00R\tceBoolean\x12\x1f\n" +
	"\n" +
	"ce_integer\x18\x02 \x01(\x05H\x00R\tceInteger\x12\x1d\n" +
	"\tce_string\x18\x03 \x01(\tH\x00R\bceString\x12\x1b\n" +
	"\bce_bytes\x18\x04 \x01(\fH\x00R\aceBytes\x12\x17\n" +
	"\x06ce_uri\x18\x05 \x01(\tH\x00R\x05ceUri\x12*\n" +
	"\x10ce_uri_reference\x18\x06 \x01(\tH\x00R\x0eceUriReference\x12?\n" +
	"\fce_timestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vceTimestampB\x06\n" +
	"\x04attr:@\n" +
	"\n" +
	"event_type\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\tR\teventType:G\n" +
	"\x0fis_aggregate_id\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\bR\risAggregateIdB\x9a\x01\n" +
	"\x0fcom.registry.v1B\rEnvelopeProtoP\x01Z&schema-registry/registry/v1;registryv1\xa2\x02\x03RXX\xaa\x02\vRegistry.V1\xca\x02\vRegistry\\V1\xe2\x02\x17Registry\\V1\\GPBMetadata\xea\x02\fRegistry::V1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_registry_v1_envelope_proto_rawDescOnce sync.Once
	file_registry_v1_envelope_proto_rawDescData []byte
)

func file_registry_v1_envelope_proto_rawDescGZIP() []byte {
	file_registry_v1_envelope_proto_rawDescOnce.Do(func() {
		file_registry_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_v1_envelope_proto_rawDesc), len(file_registry_v1_envelope_proto_rawDesc)))
	})
	return file_registry_v1_envelope_proto_rawDescData
}

var file_registry_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_registry_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil),                    // 0: registry.v1.Envelope
	(*CloudEventAttributeValue)(nil),    // 1: registry.v1.CloudEventAttributeValue
	nil,                                 // 2: registry.v1.Envelope.AttributesEntry
	(*timestamppb.Timestamp)(nil),       // 3: google.protobuf.Timestamp
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 5: google.protobuf.FieldOptions
}
var file_registry_v1_envelope_proto_depIdxs = []int32{
	2, // 0: registry.v1.Envelope.attributes:type_name -> registry.v1.Envelope.AttributesEntry
	3, // 1: registry.v1.Envelope.time:type_name -> google.protobuf.Timestamp
	3, // 2: registry.v1.CloudEventAttributeValue.ce_timestamp:type_name -> google.protobuf.Timestamp
	1, // 3: registry.v1.Envelope.AttributesEntry.value:type_name -> registry.v1.CloudEventAttributeValue
	4, // 4: registry.v1.event_type:extendee -> google.protobuf.MessageOptions
	5, // 5: registry.v1.is_aggregate_id:extendee -> google.protobuf.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	4, // [4:6] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_registry_v1_envelope_proto_init() }
func file_registry_v1_envelope_proto_init() {
	if File_registry_v1_envelope_proto != nil {
		return
	}
	file_registry_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_BinaryData)(nil),
		(*Envelope_TextData)(nil),
	}
	file_registry_v1_envelope_proto_msgTypes[1].OneofWrappers = []any{
		(*CloudEventAttributeValue_CeBoolean)(nil),
		(*CloudEventAttributeValue_CeInteger)(nil),
		(*CloudEventAttributeValue_CeString)(nil),
		(*CloudEventAttributeValue_CeBytes)(nil),
		(*CloudEventAttributeValue_CeUri)(nil),
		(*CloudEventAttributeValue_CeUriReference)(nil),
		(*CloudEventAttributeValue_CeTimestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_v1_envelope_proto_rawDesc), len(file_registry_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_registry_v1_envelope_proto_goTypes,
		DependencyIndexes: file_registry_v1_envelope_proto_depIdxs,
		MessageInfos:      file_registry_v1_envelope_proto_msgTypes,
		ExtensionInfos:    file_registry_v1_envelope_proto_extTypes,
	}.Build()
	File_registry_v1_envelope_proto = out.File
	file_registry_v1_envelope_proto_goTypes = nil
	file_registry_v1_envelope_proto_depIdxs = nil
}
