# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registry/v1/envelope.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'registry/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aregistry/v1/envelope.proto\x12\x0bregistry.v1\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x03\n\x08\x45nvelope\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06source\x18\x02 \x01(\tR\x06source\x12 \n\x0bspecversion\x18\x03 \x01(\tR\x0bspecversion\x12\x12\n\x04type\x18\x04 \x01(\tR\x04type\x12\x45\n\nattributes\x18\x05 \x03(\x0b\x32%.registry.v1.Envelope.AttributesEntryR\nattributes\x12!\n\x0b\x62inary_data\x18\x06 \x01(\x0cH\x00R\nbinaryData\x12\x1d\n\ttext_data\x18\x07 \x01(\tH\x00R\x08textData\x12.\n\x04time\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x04time\x1a\x64\n\x0f\x41ttributesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12;\n\x05value\x18\x02 \x01(\x0b\x32%.registry.v1.CloudEventAttributeValueR\x05value:\x02\x38\x01\x42\x0c\n\ndata_oneof\"\xa6\x02\n\x18\x43loudEventAttributeValue\x12\x1f\n\nce_boolean\x18\x01 \x01(\x08H\x00R\tceBoolean\x12\x1f\n\nce_integer\x18\x02 \x01(\x05H\x00R\tceInteger\x12\x1d\n\tce_string\x18\x03 \x01(\tH\x00R\x08\x63\x65String\x12\x1b\n\x08\x63\x65_bytes\x18\x04 \x01(\x0cH\x00R\x07\x63\x65\x42ytes\x12\x17\n\x06\x63\x65_uri\x18\x05 \x01(\tH\x00R\x05\x63\x65Uri\x12*\n\x10\x63\x65_uri_reference\x18\x06 \x01(\tH\x00R\x0e\x63\x65UriReference\x12?\n\x0c\x63\x65_timestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00R\x0b\x63\x65TimestampB\x06\n\x04\x61ttr:@\n\nevent_type\x12\x1f.google.protobuf.MessageOptions\x18\xd1\x86\x03 \x01(\tR\teventType:G\n\x0fis_aggregate_id\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x08R\risAggregateIdB\xb8\x01\n-com.github.cgund98.schemaregistry.registry.v1B\rEnvelopeProtoP\x01Z&schema-registry/registry/v1;registryv1\xa2\x02\x03RXX\xaa\x02\x0bRegistry.V1\xca\x02\x0bRegistry\\V1\xe2\x02\x17Registry\\V1\\GPBMetadata\xea\x02\x0cRegistry::V1\x92\x03\x02\x08\x02\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.github.cgund98.schemaregistry.registry.v1B\rEnvelopeProtoP\001Z&schema-registry/registry/v1;registryv1\242\002\003RXX\252\002\013Registry.V1\312\002\013Registry\\V1\342\002\027Registry\\V1\\GPBMetadata\352\002\014Registry::V1\222\003\002\010\002'
  _globals['_ENVELOPE_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_ENVELOPE_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_ENVELOPE']._serialized_start=111
  _globals['_ENVELOPE']._serialized_end=516
  _globals['_ENVELOPE_ATTRIBUTESENTRY']._serialized_start=402
  _globals['_ENVELOPE_ATTRIBUTESENTRY']._serialized_end=502
  _globals['_CLOUDEVENTATTRIBUTEVALUE']._serialized_start=519
  _globals['_CLOUDEVENTATTRIBUTEVALUE']._serialized_end=813
# @@protoc_insertion_point(module_scope)
