from typing import Protocol

from schema_registry.registry.v1.message import ProtobufMessage


class Payload(Protocol):
    """
    Interface for an event payload DTO.

    These will be generated by the `protoc-gen-python-dto` plugin.
    """

    def aggregate_id(self) -> str: ...

    def to_protobuf(self) -> ProtobufMessage: ...

    @classmethod
    def from_protobuf(cls, data: bytes) -> "Payload": ...
