from typing import Protocol

from google.protobuf.message import Message


class Payload(Protocol):
    """
    Interface for an event payload DTO.

    These will be generated by the `protoc-gen-python-dto` plugin.
    """

    def aggregate_id(self) -> str: ...

    def to_protobuf(self) -> Message: ...

    @classmethod
    def from_protobuf(cls, data: bytes) -> "Payload": ...
