package main

import (
	"fmt"
	"path/filepath"
	"strings"
	"unicode"

	registryv1 "schema-registry/registry/v1"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func hasEventTypeOption(msg *protogen.Message) (string, bool) {
	opts := msg.Desc.Options()
	if opts == nil {
		return "", false
	}
	pm, ok := opts.(proto.Message)
	if !ok {
		return "", false
	}
	if !proto.HasExtension(pm, registryv1.E_EventType) {
		return "", false
	}
	val := proto.GetExtension(pm, registryv1.E_EventType)
	s, ok := val.(string)
	if !ok || strings.TrimSpace(s) == "" {
		return "", false
	}
	return s, true
}

func getAggregateIDField(msg *protogen.Message) (*protogen.Field, error) {
	var found *protogen.Field
	for _, field := range msg.Fields {
		opts := field.Desc.Options()
		if opts == nil {
			continue
		}
		pm, ok := opts.(proto.Message)
		if !ok {
			continue
		}
		if !proto.HasExtension(pm, registryv1.E_IsAggregateId) {
			continue
		}
		val := proto.GetExtension(pm, registryv1.E_IsAggregateId)
		if b, ok := val.(bool); !ok || !b {
			continue
		}
		if found != nil {
			return nil, fmt.Errorf(
				"message %s: multiple fields have (registry.v1.is_aggregate_id) = true (e.g. %s and %s)",
				msg.Desc.FullName(), found.Desc.Name(), field.Desc.Name(),
			)
		}
		found = field
	}
	if found == nil {
		return nil, fmt.Errorf(
			"message %s: no field has (registry.v1.is_aggregate_id) = true; exactly one is required",
			msg.Desc.FullName(),
		)
	}
	return found, nil
}

// kotlinPackageFromProtoPath returns the Kotlin package for a proto path (e.g. user/v1 -> com.user.v1).
func kotlinPackageFromProtoPath(protoDir string) string {
	slash := filepath.ToSlash(protoDir)
	parts := strings.Split(slash, "/")
	return "com." + strings.Join(parts, ".")
}

// kotlinPackageForFile returns the Kotlin package for the generated file, using java_package if set.
func kotlinPackageForFile(file *protogen.File) string {
	if opts := file.Proto.GetOptions(); opts != nil {
		if pkg := opts.GetJavaPackage(); pkg != "" {
			return pkg
		}
	}
	dir := filepath.Dir(file.Desc.Path())
	return kotlinPackageFromProtoPath(dir)
}

// kotlinEventsFilename returns the output path for the Kotlin events file (e.g. com/user/v1/EventExtensions.kt).
func kotlinEventsFilename(protoPath string, pkg string) string {
	return strings.ReplaceAll(pkg, ".", "/") + "/EventExtensions.kt"
}

// kotlinPropertyName returns the Kotlin property name for a field (e.g. UserId -> userId).
func kotlinPropertyName(goName string) string {
	if goName == "" {
		return goName
	}
	r := rune(goName[0])
	return string(unicode.ToLower(r)) + goName[1:]
}

func quoteKotlinString(s string) string {
	// Escape backslash and double quote for Kotlin string literal.
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 || r == 0x7f {
				b.WriteString(fmt.Sprintf("\\u%04x", r))
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

func generateFile(gen *protogen.Plugin, file *protogen.File) error {
	var events []struct {
		msg       *protogen.Message
		eventType string
		aggField  *protogen.Field
	}
	for _, msg := range file.Messages {
		eventType, ok := hasEventTypeOption(msg)
		if !ok {
			continue
		}
		aggField, err := getAggregateIDField(msg)
		if err != nil {
			gen.Error(err)
			return err
		}
		events = append(events, struct {
			msg       *protogen.Message
			eventType string
			aggField  *protogen.Field
		}{msg, eventType, aggField})
	}
	if len(events) == 0 {
		return nil
	}

	protoPath := file.Desc.Path()
	pkg := kotlinPackageForFile(file)
	filename := kotlinEventsFilename(protoPath, pkg)
	g := gen.NewGeneratedFile(filename, protogen.GoImportPath(pkg))

	g.P("// Code generated by protoc-gen-kotlin-events. DO NOT EDIT.")
	g.P("// source: ", protoPath)
	g.P()
	g.P("package ", pkg)
	g.P()
	for _, e := range events {
		msg := e.msg
		eventType := e.eventType
		agg := e.aggField
		receiver := msg.GoIdent.GoName
		prop := kotlinPropertyName(agg.GoName)
		g.P("/** Event type for ", receiver, " */")
		g.P("public fun ", receiver, ".eventType(): kotlin.String = ", quoteKotlinString(eventType))
		g.P()
		g.P("/** Aggregate ID for ", receiver, " */")
		if agg.Desc.Kind() == protoreflect.StringKind {
			g.P("public fun ", receiver, ".aggregateId(): kotlin.String = ", prop)
		} else {
			g.P("public fun ", receiver, ".aggregateId(): kotlin.String = ", prop, ".toString()")
		}
		g.P()
	}
	return nil
}

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)
		gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO2
		gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2023

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generateFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}
