# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/v1/user.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'user/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from schema_registry.registry.v1 import envelope_pb2 as registry_dot_v1_dot_envelope__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user/v1/user.proto\x12\x07user.v1\x1a google/protobuf/descriptor.proto\x1a\x1aregistry/v1/envelope.proto\"\x8d\x01\n\x0bUserCreated\x12\x1d\n\x07user_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01R\x06userId\x12\x1b\n\tuser_name\x18\x02 \x01(\tR\x08userName\x12\x14\n\x05\x65mail\x18\x03 \x01(\tR\x05\x65mail\x12\x17\n\x03\x61ge\x18\x04 \x01(\x05\x42\x05\xaa\x01\x02\x08\x01R\x03\x61ge:\x13\x8a\xb5\x18\x0fuser.v1.created\"\x8d\x01\n\x0bUserUpdated\x12\x1d\n\x07user_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01R\x06userId\x12\x1b\n\tuser_name\x18\x02 \x01(\tR\x08userName\x12\x14\n\x05\x65mail\x18\x03 \x01(\tR\x05\x65mail\x12\x17\n\x03\x61ge\x18\x04 \x01(\x05\x42\x05\xaa\x01\x02\x08\x01R\x03\x61ge:\x13\x8a\xb5\x18\x0fuser.v1.updated\"A\n\x0bUserDeleted\x12\x1d\n\x07user_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01R\x06userId:\x13\x8a\xb5\x18\x0fuser.v1.deletedB\x98\x01\n)com.github.cgund98.schemaregistry.user.v1B\tUserProtoP\x01Z\x1eschema-registry/user/v1;userv1\xa2\x02\x03UXX\xaa\x02\x07User.V1\xca\x02\x07User\\V1\xe2\x02\x13User\\V1\\GPBMetadata\xea\x02\x08User::V1\x92\x03\x02\x08\x02\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.github.cgund98.schemaregistry.user.v1B\tUserProtoP\001Z\036schema-registry/user/v1;userv1\242\002\003UXX\252\002\007User.V1\312\002\007User\\V1\342\002\023User\\V1\\GPBMetadata\352\002\010User::V1\222\003\002\010\002'
  _globals['_USERCREATED'].fields_by_name['user_id']._loaded_options = None
  _globals['_USERCREATED'].fields_by_name['user_id']._serialized_options = b'\220\265\030\001'
  _globals['_USERCREATED'].fields_by_name['age']._loaded_options = None
  _globals['_USERCREATED'].fields_by_name['age']._serialized_options = b'\252\001\002\010\001'
  _globals['_USERCREATED']._loaded_options = None
  _globals['_USERCREATED']._serialized_options = b'\212\265\030\017user.v1.created'
  _globals['_USERUPDATED'].fields_by_name['user_id']._loaded_options = None
  _globals['_USERUPDATED'].fields_by_name['user_id']._serialized_options = b'\220\265\030\001'
  _globals['_USERUPDATED'].fields_by_name['age']._loaded_options = None
  _globals['_USERUPDATED'].fields_by_name['age']._serialized_options = b'\252\001\002\010\001'
  _globals['_USERUPDATED']._loaded_options = None
  _globals['_USERUPDATED']._serialized_options = b'\212\265\030\017user.v1.updated'
  _globals['_USERDELETED'].fields_by_name['user_id']._loaded_options = None
  _globals['_USERDELETED'].fields_by_name['user_id']._serialized_options = b'\220\265\030\001'
  _globals['_USERDELETED']._loaded_options = None
  _globals['_USERDELETED']._serialized_options = b'\212\265\030\017user.v1.deleted'
  _globals['_USERCREATED']._serialized_start=94
  _globals['_USERCREATED']._serialized_end=235
  _globals['_USERUPDATED']._serialized_start=238
  _globals['_USERUPDATED']._serialized_end=379
  _globals['_USERDELETED']._serialized_start=381
  _globals['_USERDELETED']._serialized_end=446
# @@protoc_insertion_point(module_scope)
