// Code generated by protoc-gen-go-events. DO NOT EDIT.
// source: user/v1/user.proto

package userv1

// EventType returns the event type string for UserCreated.
func (x *UserCreated) EventType() string {
	return "user.v1.created"
}

// AggregateId returns the aggregate ID for UserCreated.
func (x *UserCreated) AggregateId() string {
	return x.GetUserId()
}

// EventType returns the event type string for UserUpdated.
func (x *UserUpdated) EventType() string {
	return "user.v1.updated"
}

// AggregateId returns the aggregate ID for UserUpdated.
func (x *UserUpdated) AggregateId() string {
	return x.GetUserId()
}

// EventType returns the event type string for UserDeleted.
func (x *UserDeleted) EventType() string {
	return "user.v1.deleted"
}

// AggregateId returns the aggregate ID for UserDeleted.
func (x *UserDeleted) AggregateId() string {
	return x.GetUserId()
}
